// Fichier généré par ffigen à partir de native/stitcher/include/sary_stitcher.h.
// Ne pas modifier à la main : relancer `dart run ffigen --config ffigen.yaml`.
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Bindings FFI du module C++ d'assemblage (native/stitcher).
class SaryStitcherBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SaryStitcherBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SaryStitcherBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Version d'OpenCV liée au module (chaîne statique).
  ffi.Pointer<ffi.Char> sary_opencv_version() {
    return _sary_opencv_version();
  }

  late final _sary_opencv_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'sary_opencv_version',
      );
  late final _sary_opencv_version = _sary_opencv_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Assemble les photos en une image équirectangulaire 360° (2:1).
  /// Renvoie un code SARY_OK / SARY_ERR_*.
  int sary_stitch(
    ffi.Pointer<SaryStitchParams> params,
    ffi.Pointer<SaryStitchResult> result,
  ) {
    return _sary_stitch(params, result);
  }

  late final _sary_stitchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<SaryStitchParams>,
            ffi.Pointer<SaryStitchResult>,
          )
        >
      >('sary_stitch');
  late final _sary_stitch = _sary_stitchPtr
      .asFunction<
        int Function(
          ffi.Pointer<SaryStitchParams>,
          ffi.Pointer<SaryStitchResult>,
        )
      >();
}

const int SARY_ERR_CANCELLED = 4;

const int SARY_ERR_IMAGE_READ = 2;

const int SARY_ERR_INVALID_ARGS = 1;

const int SARY_ERR_OPENCV = 5;

const int SARY_ERR_OUT_OF_MEMORY = 3;

const int SARY_ERR_WRITE = 6;

const int SARY_OK = 0;

/// Paramètres d'un assemblage.
final class SaryStitchParams extends ffi.Struct {
  /// Nombre de photos.
  @ffi.Int32()
  external int image_count;

  /// Chemins des JPEG (UTF-8). L'orientation EXIF est appliquée au décodage.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> image_paths;

  /// Rotations mesurées par les capteurs : image_count matrices 3×3, ligne
  /// par ligne. Chaque matrice envoie le repère caméra OpenCV (x à droite,
  /// y vers le bas, z vers l'avant) dans le repère monde de la sphère
  /// (y vers le bas, z au centre du panorama).
  external ffi.Pointer<ffi.Float> rotations;

  /// Champ de vision horizontal d'une photo décodée, en degrés.
  @ffi.Float()
  external double hfov_deg;

  /// Largeur de l'image équirectangulaire (hauteur = largeur / 2).
  @ffi.Int32()
  external int output_width;

  /// Qualité JPEG de sortie (1-100).
  @ffi.Int32()
  external int jpeg_quality;

  /// Résolutions de travail en mégapixels : détection des points-clés,
  /// recherche des raccords, composition (≤ 0 : résolution d'origine).
  @ffi.Float()
  external double work_megapix;

  @ffi.Float()
  external double seam_megapix;

  @ffi.Float()
  external double compose_megapix;

  /// Nombre maximal de points-clés ORB par photo (≤ 0 : 1500).
  @ffi.Int32()
  external int max_features;

  /// Seules les paires dont les axes de visée sont séparés de moins de cet
  /// angle (degrés) sont mises en correspondance.
  @ffi.Float()
  external double neighbor_max_angle_deg;

  /// 1 : affiner les rotations par points-clés + bundle adjustment ;
  /// 0 : utiliser directement les rotations des capteurs.
  @ffi.Int32()
  external int refine;

  /// Chemin du JPEG équirectangulaire produit.
  external ffi.Pointer<ffi.Char> output_path;

  /// Progression 0..1 écrite par le module (peut être NULL). Lue en
  /// parallèle par l'isolate principal.
  external ffi.Pointer<ffi.Float> progress;

  /// Mis à une valeur non nulle par l'isolate principal pour demander
  /// l'annulation (peut être NULL).
  external ffi.Pointer<ffi.Int32> cancel;

  static ffi.Pointer<SaryStitchParams> $allocate(
    ffi.Allocator $allocator, {
    required int image_count,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> image_paths,
    required ffi.Pointer<ffi.Float> rotations,
    required double hfov_deg,
    required int output_width,
    required int jpeg_quality,
    required double work_megapix,
    required double seam_megapix,
    required double compose_megapix,
    required int max_features,
    required double neighbor_max_angle_deg,
    required int refine,
    required ffi.Pointer<ffi.Char> output_path,
    required ffi.Pointer<ffi.Float> progress,
    required ffi.Pointer<ffi.Int32> cancel,
  }) => $allocator<SaryStitchParams>()
    ..ref.image_count = image_count
    ..ref.image_paths = image_paths
    ..ref.rotations = rotations
    ..ref.hfov_deg = hfov_deg
    ..ref.output_width = output_width
    ..ref.jpeg_quality = jpeg_quality
    ..ref.work_megapix = work_megapix
    ..ref.seam_megapix = seam_megapix
    ..ref.compose_megapix = compose_megapix
    ..ref.max_features = max_features
    ..ref.neighbor_max_angle_deg = neighbor_max_angle_deg
    ..ref.refine = refine
    ..ref.output_path = output_path
    ..ref.progress = progress
    ..ref.cancel = cancel;
}

/// Compte rendu d'un assemblage.
final class SaryStitchResult extends ffi.Struct {
  /// 1 si les rotations affinées ont été retenues, 0 si celles des capteurs.
  @ffi.Int32()
  external int refined;

  /// Nombre de paires de photos avec des correspondances fiables.
  @ffi.Int32()
  external int matched_pairs;

  /// Écart médian entre rotations affinées et rotations capteurs (degrés),
  /// ou -1 si l'affinage n'a pas abouti.
  @ffi.Float()
  external double median_correction_deg;

  /// Durée totale en millisecondes.
  @ffi.Int32()
  external int elapsed_ms;

  /// Message d'erreur ou de diagnostic (UTF-8, terminé par 0).
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> message;
}
